### ISSUE TITLE
Host on github pages

### ISSUE THREAD

**Issue by 3noch** [dalaing/intro-to-reflex-talk#1]
If it's just static content could you host the result via gh-pages?

**Comment by dalaing** [comment]
Good idea! Working on it...

**Comment by dalaing** [comment]
Although it doesn't make much sense without my patter over the top of it :)

**Comment by dalaing** [comment]
Now available [here](http://dlaing.org/intro-to-reflex-talk)

**Comment by 3noch** [comment]
Thank you!
